version: "3.4"

services:
  ibmmq:
    image: "ibm-mqadvanced-server-dev:9.3.5.0-arm64"
    container_name: "QM1"
    restart: always
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - "qm1data:/mnt/mqm"
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_PASSWORD=passw0rd
      - MQ_ADMIN_PASSWORD=passw0rd

volumes:
  qm1data:
    driver: local
